import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      spacing: {
        "gutter": "1rem",
        "margin": "1.5rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-base": "1.25rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "2.5rem",
        "space-3xl": "3rem",
        "space-4xl": "4rem",
      },
      fontFamily: {
        "body-default": ["Inter", "sans-serif"],
        "code-inline": ["JetBrains Mono", "monospace"],
        "code-metric": ["JetBrains Mono", "monospace"],
        "title-md": ["Inter", "sans-serif"],
        "body-compact": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-ui": ["Inter", "sans-serif"],
        "display-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-default": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "code-inline": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "code-metric": ["12px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "title-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-compact": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-ui": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        
        error: "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",

        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        
        tertiary: "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        
        "accent-primary": "var(--color-accent-primary)",
        "on-accent-primary": "var(--color-on-accent-primary)",
        "accent-container": "var(--color-accent-container)",
        "on-accent-container": "var(--color-on-accent-container)",
        "accent-fixed": "var(--color-accent-fixed)",
        "on-accent-fixed": "var(--color-on-accent-fixed)",

        "accent-secondary": "var(--color-accent-secondary)",
        "on-accent-secondary": "var(--color-on-accent-secondary)",
        "accent-secondary-container": "var(--color-accent-secondary-container)",
        "on-accent-secondary-container": "var(--color-on-accent-secondary-container)",
        "accent-secondary-fixed": "var(--color-accent-secondary-fixed)",
        "on-accent-secondary-fixed": "var(--color-on-accent-secondary-fixed)",
      },
    },
  },
  plugins: [],
} satisfies Config;


